services:
  # Main web service
  - type: web
    name: pipelineforge
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pipelineforge-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: pipelineforge-db
    databaseName: pipelineforge
    plan: starter
    region: oregon
    postgresMajorVersion: 15
